### ISSUE TITLE
Error Message in online.py

### ISSUE THREAD

**Issue by MrBelly** [ICSResearch/TrapAttention#1]
Dear Author,

I hope you are having a good day. I have encountered an error in online.py as in the attachments about the matrix dimensions.  I am trying to construct a depth map of a single image.  I have used the camera parameters and images from Kaggle for this Python file.  Even I choose the camera matrix as 3 y 3 matrix, I am still getting that error.  I would appreciate your help.  Thanks in advance.

My best regards,
![error_mesage](https://github.com/ICSResearch/TrapAttention/assets/72914346/d6a6e9b4-3e89-4432-a70b-feed006c13d7)
![error_mesage](https://github.com/ICSResearch/TrapAttention/assets/72914346/b0a12403-6479-47c7-b541-da6eaa4703ff)

**Comment by ICSResearch** [comment]
I'm very sorry. This file was used for testing the code in the early stages of the experiment and may be incompatible with some modifications made later in the experiment. We have removed this file.
